# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # handler_id: session.handler.native_file
        
        cookie_lifetime: 3600 # 1 heure = 60 min * 60 s = 
        gc_maxlifetime: 3600
        cookie_secure: true
        sid_bits_per_character: 5
        cookie_samesite: lax
        # storage_factory_id: session.storage.factory.native_file

    #esi: true
    #fragments: true
    php_errors:
        log: true
        

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
